repo: "insect-injector"
canvasCourse: "467503"
canvasAssignment: "4202523"

naming: true
commits: 1

html:
  - path: "index.html"
    locked: true

css:
  - path: "css/main.css"
    locked: true

js:
  - path: "js/main.js"
    valid: true
    bestPractices: true

screenshots:
  - path: "index.html"
    sizes: [320]
